# Generated by Django 6.0.1 on 2026-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识 Token 用途', max_length=100, verbose_name='Token 名称')),
                ('key', models.CharField(help_text='Token 的哈希值，用于验证', max_length=64, unique=True, verbose_name='Token Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, help_text='为空表示永不过期', null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
